services:
  - type: web
    name: questree
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_GA4_MEASUREMENT_ID
        value: G-P007DSD3SK
    healthCheckPath: /api/health
